app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

nao_login:
    path: /login

nao_logout:
    path: /logout

nao_home:
    path: /
    defaults: { _controller: AppBundle:App:index }

nao_dashboard:
    path: /dashboard/
    defaults: { _controller: UserBundle:User:dashboard }

nao_profile:
    path: /profile/

nao_admin:
    path: /admin/
    defaults: { _controller: UserBundle:User:admin }

nao_show_user:
    path: /user/{id}/
    defaults: { _controller: UserBundle:User:showUser }
    requirements:
            id: \d+

nao_edit_user:
     path: /user/{id}/edit/
     defaults: { _controller: UserBundle:User:editUser }
     requirements:
            id: \d+

nao_list_users:
    path: /user/all/
    defaults: { _controller: UserBundle:User:listUsers }
