app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

nao_login:
    path: /login

nao_logout:
    path: /logout

nao_home:
    path: /
    defaults: { _controller: AppBundle:App:index }

nao_dashboard:
    path: /dashboard/
    defaults: { _controller: UserBundle:User:dashboard }

nao_profile:
    path: /profile/

nao_admin:
    path: /admin/
    defaults: { _controller: UserBundle:User:admin }

nao_show_user:
    path: /user/{id}/
    defaults: { _controller: UserBundle:User:showUser }
    requirements:
            id: \d+

nao_edit_user:
     path: /user/{id}/edit/
     defaults: { _controller: UserBundle:User:editUser }
     requirements:
            id: \d+

nao_list_users:
    path: /user/all/
    defaults: { _controller: UserBundle:User:listUsers }

nao_obs_add:
    path: /observation/add
    defaults:
        _controller: ObservationBundle:Observation:add

nao_obs_check:
    path: /observation/check/{id}
    defaults:
        _controller: ObservationBundle:Observation:check
    requirements:
        id: \d+

nao_obs_show:
    path: /observation/{id}
    defaults:
        _controller: ObservationBundle:Observation:show
    requirements:
        id: \d+

nao_obs_search:
    path: /observation/search
    defaults:
        _controller: ObservationBundle:Observation:search

nao_obs_search_result:
    path: /observation/result/{view}/{filter}
    defaults:
        _controller: ObservationBundle:Observation:result
        view:   null
        filter: null
    requirements:
        view:   \w*
        filter: \w*