app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

nao_home:
    path: /
    defaults: { _controller: AppBundle:App:index }

nao_dashboard:
    path: /dashboard
    defaults: { _controller: UserBundle:User:dashboard }

nao_admin:
    path: /admin
    defaults: { _controller: UserBundle:User:admin }

nao_show_user:
    path: /user/{id}
    defaults: { _controller: UserBundle:User:showUser }