app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

nao_home:
    path: /
    defaults: { _controller: AppBundle:App:index }

nao_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login}

nao_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout}

nao_dashboard:
    path: /dashboard/
    defaults: { _controller: UserBundle:User:dashboard }

nao_stat:
    path: /stats/
    defaults: { _controller: UserBundle:User:stats }

nao_profile:
    path: /profile/
    defaults: { _controller: FOSUserBundle:Profile:show}

nao_profile_edit:
    path: /profile/edit/
    defaults: { _controller: FOSUserBundle:Profile:edit }

nao_admin:
    path: /admin/
    defaults: { _controller: UserBundle:User:dashboard }

nao_show_user:
    path: /user/{id}/
    defaults: { _controller: UserBundle:User:showUser }
    requirements:
            id: \d+

nao_edit_user:
     path: /user/{id}/edit/
     defaults: { _controller: UserBundle:User:editUser }
     requirements:
            id: \d+

nao_edit_user_avatar:
    path: /{id}/editUserAvatar
    defaults:
        _controller: UserBundle:User:editUserAvatar

nao_list_users:
    path: /user/all/
    defaults: { _controller: UserBundle:User:listUsers }

nao_obs_add:
    path: /observation/add
    defaults:
        _controller: ObservationBundle:Observation:add

nao_ajax_bird_name:
    path: /observation/ajax/birdName/{birdName}
    defaults:
        _controller: ObservationBundle:Observation:birdNameAutoComplete
        birdName: ''
    requirements:
        birdName: .*

nao_obs_check:
    path: /observation/check/{id}
    defaults:
        _controller: ObservationBundle:Observation:check
    requirements:
        id: \d+

nao_obs_show:
    path: /observation/{id}
    defaults:
        _controller: ObservationBundle:Observation:show
    requirements:
        id: \d+

nao_obs_user_list:
    path: /observation/userList
    defaults:
        _controller: ObservationBundle:Observation:showUserList

nao_obs_check_list:
    path: /observation/checkList
    defaults:
        _controller: ObservationBundle:Observation:showCheckList

nao_obs_search:
    path: /observation/search
    defaults:
        _controller: ObservationBundle:Observation:search

nao_obs_search_result:
    path: /observation/result/{view}/{filter}
    defaults:
        _controller: ObservationBundle:Observation:result
        view:   null
        filter: null
    requirements:
        view:   \w*
        filter: \w*