app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /profile/message

nao_home:
    path: /
    defaults: { _controller: AppBundle:App:index }

nao_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login}

nao_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout}

nao_dashboard:
    path: /dashboard/
    defaults: { _controller: UserBundle:User:dashboard }

nao_stats:
    path: /stats/
    defaults: { _controller: UserBundle:User:stats }

nao_profile:
    path: /profile/
    defaults: { _controller: FOSUserBundle:Profile:show }

nao_profile_edit:
    path: /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

nao_admin:
    path: /admin/
    defaults: { _controller: UserBundle:User:dashboard }

nao_show_user:
    path: /user/{id}/
    defaults: { _controller: UserBundle:User:showUser }
    requirements:
            id: \d+

nao_edit_user:
     path: /user/{id}/edit/
     defaults: { _controller: UserBundle:User:editUser }
     requirements:
            id: \d+

nao_edit_user_avatar:
    path: /{id}/editUserAvatar
    defaults: { _controller: UserBundle:User:editUserAvatar }

nao_activate_user:
    path: /user/{id}/activate
    defaults: { _controller: UserBundle:User:activateUser }

nao_deactivate_user:
    path: /user/{id}/deactivate
    defaults: { _controller: UserBundle:User:deactivateUser }

nao_list_users:
    path: /user/all/
    defaults: { _controller: UserBundle:User:listUsers }

nao_blog_index:
    path: /blog/
    defaults: { _controller: BlogBundle:Blog:index }

nao_blog_add_article:
    path: /blog/add/
    defaults: { _controller: BlogBundle:Blog:addArticle }

nao_blog_delete_article:
    path: /blog/{id}/delete
    defaults: { _controller: BlogBundle:Blog:deleteArticle }

nao_blog_edit_article:
    path: /blog/{id}/edit
    defaults: { _controller: BlogBundle:Blog:editArticle }

nao_blog_show_article:
    path: /blog/article/{slug}/
    defaults: { _controller: BlogBundle:Blog:showArticle }

nao_blog_list_articles:
    path: /blog/all/
    defaults: { _controller: BlogBundle:Blog:listArticle }

nao_blog_list_comments:
    path: /blog/comments/all
    defaults: { _controller: BlogBundle:Blog:listComments }

nao_blog_edit_comment:
    path: /blog/comment/{id}/edit
    defaults: { _controller: BlogBundle:Blog:editComment }

nao_blog_delete_comment:
    path: /blog/comment/{id}/delete
    defaults: { _controller: BlogBundle:Blog:deleteArticle }

nao_obs_add:
    path: /observation/add
    defaults:
        _controller: ObservationBundle:Observation:add

nao_obs_check:
    path: /observation/check/{id}
    defaults:
        _controller: ObservationBundle:Observation:check
    requirements:
        id: \d+

nao_obs_show:
    path: /observation/{id}
    defaults:
        _controller: ObservationBundle:Observation:show
    requirements:
        id: \d+

nao_obs_edit:
    path: /observation/edit/{id}
    defaults:
        _controller: ObservationBundle:Observation:edit
    requirements:
        id: \d+

nao_obs_remove:
    path: /observation/remove/{id}
    defaults:
        _controller: ObservationBundle:Observation:remove
    requirements:
        id: \d+

nao_obs_user_list:
    path: /observation/userList
    defaults:
        _controller: ObservationBundle:Observation:showUserList

nao_obs_check_list:
    path: /observation/checkList
    defaults:
        _controller: ObservationBundle:Observation:showCheckList

nao_obs_search:
    path: /observation/search
    defaults:
        _controller: ObservationBundle:Observation:search

nao_ajax_obs_list:
    path: /observation/ajax/obsList
    defaults:
        _controller: ObservationBundle:Ajax:obsMarker

nao_ajax_bird_name:
    path: /observation/ajax/birdName/{birdName}
    defaults:
        _controller: ObservationBundle:Ajax:birdNameAutoComplete
        birdName: ''
    requirements:
        birdName: .*

nao_ajax_urls_taxon:
    path: /observation/ajax/urlsTaxon/{birdName}
    defaults:
        _controller: ObservationBundle:Ajax:getUrlsTaxon
        birdName: ''
    requirements:
        birdName: .*

nao_obs_search_result:
    path: /observation/result/{view}/{filter}
    defaults:
        _controller: ObservationBundle:Observation:result
        view:   null
        filter: null
    requirements:
        view:   \w*
        filter: \w*

nao_ajax_vote_obs:
    path: /observation/ajax/vote/{id}
    defaults:
        _controller: ObservationBundle:Ajax:voteObservation
    requirements:
        id: \d+

nao_landing_page:
    path: /landing-page/
    defaults: { _controller: AppBundle:App:landingPage }

nao_second_landing_page:
    path: /landing-page-2/
    defaults: { _controller: AppBundle:App:secondLandingPage }

nao_quiz:
    path: /quiz/
    defaults: { _controller: AppBundle:App:quiz }

nao_contact:
    path: /contact/
    defaults: { _controller: AppBundle:App:createContactForm }

nao_footer_contact:
    path: /footerContact/
    defaults: { _controller: AppBundle:App:submitFooterForm }

nao_join_association:
    path: /join/
    defaults: { _controller: AppBundle:App:join }

nao_partners:
    path: /partners/
    defaults: { _controller: AppBundle:App:partners }

nao_presse:
    path: /presse/
    defaults: { _controller: AppBundle:App:presse }

nao_credits:
    path: /credits/
    defaults: { _controller: AppBundle:App:credits }