services:
#
#   VALIDATOR
#   
    observation.validator.birdNameExists:
        class: ObservationBundle\Validator\BirdNameExistsValidator
        arguments:
          - "@doctrine.orm.entity_manager"
        public: true
        tags:
          - { name: validator.constraint_validator, alias: observation.birdNameExists }
#
#   FORM
#
    observation.form.search:
        class: ObservationBundle\Form\SearchType
        arguments:
          - "@observation.searchFiltered"
        public: true
        tags: [form.type]
#
#   SERVICE
#
    observation.geoloc:
        class: ObservationBundle\Service\Geoloc
        arguments:
          - "%google_map_api%"
        public: true

    observation.searchFiltered:
        class: ObservationBundle\Service\SearchFiltered
        arguments:
          - "@doctrine.orm.entity_manager"
        public: true

    observation.taxonFinder:
        class: ObservationBundle\Service\TaxonFinder
        arguments:
          - "@doctrine.orm.entity_manager"
        public: true

    observation.obsValidation:
        class: ObservationBundle\Service\ObsValidation
        arguments:
          - "@security.token_storage"
          - "@doctrine.orm.entity_manager"
        public: true