services:
#    observation.example:
#        class: ObservationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    observation.validator.birdNameExists:
        class: ObservationBundle\Validator\BirdNameExistsValidator
        arguments:
          - "@doctrine.orm.entity_manager"
        public: true
        tags:
          - { name: validator.constraint_validator, alias: observation.birdNameExists }

    observation.geoloc:
        class: ObservationBundle\Service\Geoloc
        arguments:
          - "%google_map_api%"
        public: true