<?php

namespace ObservationBundle\Repository;

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find a list of taxons for autocomplete field
	 * @param  string $nameVern approx birdName
	 * @return array of taxons
	 */
	public function findForAutocomplete($nameVern)
	{
		$queryBuilder = $this->createQueryBuilder('tax');
		$queryBuilder
			->where($queryBuilder->expr()->like('tax.nameVern', ':nameVern'))
			->setParameter('nameVern', $nameVern . '%')
			->andWhere('tax.cdNom = tax.cdRef')
			->orderBy('tax.nameVern', 'ASC');
		return $queryBuilder->getQuery()->getResult();
	}

	/**
	 * Find the taxon with the bird name
	 * @param  string $nameVern bird name vernaculaire
	 * @return 
	 */
	public function findByNameVern($nameVern)
	{
		$queryBuilder = $this->createQueryBuilder('tax');
		$queryBuilder
			->where($queryBuilder->expr()->like('tax.nameVern', ':nameVern'))
			->setParameter('nameVern', $nameVern)
			->andWhere('tax.cdNom = tax.cdRef');
		return $queryBuilder->getQuery()->getOneOrNullResult();
	}

	public function getFamilies()
	{
		$queryBuilder = $this->createQueryBuilder('tax');
		$queryBuilder
			->select('tax.family')
			->where('tax.cdNom = tax.cdRef')
			->andWhere("tax.nameVern != ''")
			->groupBy('tax.family');
		return $queryBuilder->getQuery()->getScalarResult();
	}

	public function getOrders()
	{
		$queryBuilder = $this->createQueryBuilder('tax');
		$queryBuilder
			->select('tax.order')
			->where('tax.cdNom = tax.cdRef')
			->andWhere("tax.nameVern != ''")
			->groupBy('tax.order');
		return $queryBuilder->getQuery()->getScalarResult();
	}

}
